Repository prometheus/alertmanager, pull requests merged in 2019-08, with the labels that each got.

#2011 Allow slashes in receivers
  asset/assets_vfsdata.go
  template/default.tmpl
  template/template.go
Labels: changelog/bugfix

#1984 Update x/sys and x/net modules to support Risc-V
  go.mod
  go.sum
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: changelog/skip

#1957 *: check Smarthost validity at config loading
  config/config.go
  config/config_test.go
  config/notifiers.go
  notify/email/email.go
  notify/email/email_test.go
Labels: changelog/change

#2012 Grouping label's expand button with grouping id
  asset/assets_vfsdata.go
  ui/app/src/Views/AlertList/Types.elm
  ui/app/src/Views/AlertList/Updates.elm
  ui/app/src/Views/AlertList/Views.elm
Labels: changelog/bugfix
